=== husqvarnagroup/smart-garden-ipso-registry/3rd-party/LWM2M-v1_1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

LWM2M XML Schema - LWM2M Editor Schema
   version - 1.1
   date    - 2018-07-10

FILE INFORMATION

  Public Reachable Information
    Path: http://www.openmobilealliance.org/tech/profiles
    Name: LWM2M-v1_1.xsd

NORMATIVE INFORMATION

  Information about this file can be found in the LWM2M online editor

  This is available at http://www.openmobilealliance.org/

  Send comments to https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues

CHANGE HISTORY

21112013 First version
06082015 Bug Fix to correct mismatch
18022016 Legal Disclaimer updated from template OMA-TEMPLATE-SUP_XSD_example-20160218-I
24032016 Changed "xs:unsignedshort" to "xs:unsignedShort"
25052016 Incorporated OMA-DM-LightweightM2M-2016-0066R01-INP_CR_Update_LWM2M_xsd
14012017 Introduction of two new elements: LWM2MObject and ObjectVersion
09022018 Introduction of two new types: "CoreLnk" and "Unsigned Integer"
12062018 Prepare for publication
10072018 Prepare for Final Approval

LEGAL DISCLAIMER

  Copyright 2018 Open Mobile Alliance Ltd.  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
  3. Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived
  from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.

  The above license is used as a license under copyright only.  Please
  reference the OMA IPR Policy for patent licensing terms:
  http://www.openmobilealliance.org/ipr.html

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LWM2M">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="Object">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Description1" type="xs:string" />
              <xs:element name="ObjectID" type="xs:unsignedShort" />
              <xs:element name="ObjectURN" type="xs:string" />
              <xs:element name="LWM2MVersion" type="xs:string" minOccurs="0"/>
              <xs:element name="ObjectVersion" type="xs:string" minOccurs="0"/>			  
              <xs:element name="MultipleInstances" >
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Multiple"/>
                    <xs:enumeration value="Single"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Mandatory" >
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Mandatory"/>
                    <xs:enumeration value="Optional"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Resources">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Item">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="xs:string" />
                          <xs:element name="Operations" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="R"/>
                                <xs:enumeration value="W"/>
                                <xs:enumeration value="RW"/>
                                <xs:enumeration value="E"/>
                                <xs:enumeration value=""/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="MultipleInstances" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Multiple"/>
                                <xs:enumeration value="Single"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Mandatory" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Mandatory"/>
                                <xs:enumeration value="Optional"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Type" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="String"/>
                                <xs:enumeration value="Integer"/>
                                <xs:enumeration value="Float"/>
                                <xs:enumeration value="Boolean"/>
                                <xs:enumeration value="Opaque"/>
                                <xs:enumeration value="Time"/>
                                <xs:enumeration value="Objlnk"/>
                                <xs:enumeration value="Unsigned Integer"/>
                                <xs:enumeration value="Corelnk"/>
                                <xs:enumeration value=""/>
                             </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="RangeEnumeration" type="xs:string" />
                          <xs:element name="Units" type="xs:string" />
                          <xs:element name="Description" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="ID" type="xs:unsignedShort" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Description2" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="ObjectType" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== husqvarnagroup/smart-garden-ipso-registry/site_map.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>SiteMap</Name>
		<Description1><![CDATA[]]></Description1>
		<ObjectID>31417</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31417:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Single</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>Available</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="2">
				<Name>UserValidatedChecksum</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Opaque</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="3">
				<Name>ZoneMapAvailable</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="4">
				<Name>SiteMapAvailable</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="5">
				<Name>GeneratedMapAvailable</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="6">
				<Name>SiteMap</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Opaque</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="7">
				<Name>GeneratedMap</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Opaque</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="8">
				<Name>ZoneMap</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Opaque</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/timeslot.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2026 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
        <Name>Timeslot</Name>
        <Description1><![CDATA[Timeslot is an instance of a schedule]]></Description1>
        <ObjectID>28182</ObjectID>
        <ObjectURN>urn:oma:lwm2m:x:28182:0.2</ObjectURN>
        <LWM2MVersion>1.1</LWM2MVersion>
        <ObjectVersion>0.2</ObjectVersion>
        <MultipleInstances>Multiple</MultipleInstances>
        <Mandatory>Optional</Mandatory>
        <Resources>
            <Item ID="1">
                <Name>start</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Time</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Intended start time in seconds since UNIX epoch. Could NOT be adjusted, the whole timeslot has to be cancelled and rescheduled instead. GW timestamp of the RUNNING state should be quite close to this one and should accurately describe the actual time of starting the action.
]]></Description>
            </Item>
            <Item ID="3">
                <Name>adjusted_stop</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Time</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>s</Units>
                <Description><![CDATA[Best known stop time (from the device standpoint). Depending on the value of `state` could be either in the past or in the future. Could be changed with `timeslot.adjust_duration()` call or with an `actuator.stop()` call. GW timestamp of the state, immediately following the RUNNING, should be very close to this value.
]]></Description>
            </Item>
            <Item ID="4">
                <Name>state</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[TSS state
Values
------
0: IDLE: No or invalid schedule
1: SCHEDULED: Schedule is active and is waiting to get scheduled
2: WILL_START: Schedule is ready to start, wait for BE decision
3: SKIPPED: Skip schedule
4: UNUSED: LB firmware used this code for SHORTEN_DURATION
5: RUNNING: Schedule is running
6: STOPPED: Schedule stopped
7: ERROR: An error occurred affecting the schedule
8: OVERWRITTEN: Schedule is overwritten because of manual watering
9: DONE: Schedule finished
10: DELETED: Schedule finished
11: REQUESTED: State machine primed for execution
]]></Description>
            </Item>
            <Item ID="6">
                <Name>initial_source</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[The reason why this timeslot was created, specifically why `start` has exactly this value. Also applies to why `adjusted_stop` has its value in case `adjustment_source` is NONE.

Values
------
0: NONE: Only relevant for adjustment.
1: PHYSICAL_BUTTON: Relevant for start reason only.
2: ERROR: Relevant for stop reason only, e.g. valve overcurrent.
3: SCHEDULE: For scheduled events.
4: BOOK_KEEPING: Only used internally by the scheduler.
10: BLUETOOTH: Used by Bluetooth application interface.
16: SMART_SYSTEM: Used by smart system app, e.g. for manual start & stop actions.
17: HOMEKIT: Used by HomeKit a.k.a. Apple Home.
18: WEB_SOCKET: Used by websocketd (for integrations like Home Assistant).
]]></Description>
            </Item>
            <Item ID="7">
                <Name>adjustment_source</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[How adjusted_stop was set. Same values as for initial_source. ]]></Description>
            </Item>
            <Item ID="8">
                <Name>pre_offset</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Magic cookie used by backend. Copied over from schedule config.]]></Description>
            </Item>
            <Item ID="9">
                <Name>actuator</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Corresponding actuator id (zero-indexed).]]></Description>
            </Item>
            <Item ID="32">
                <Name>adjust_duration</Name>
                <Operations>E</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type></Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Adjust duration of planned or running timeslot. Only has effect on timeslots in states SCHEDULED, WILL_START, RUNNING (has no effect on timeslots in all other states). Takes two arguments:
  0: integer: adjustment source. Updates the adjustment_source field.
     See initial_source above for list of available values.
  1: integer: new duration in seconds.
Uses OMA format. Example usage with bnw_cli:
  $ bnw ipso exc "$DEVICE" timeslot/0/adjust_duration "as=[0='16',1='120']"
]]></Description>
            </Item>
        </Resources>
        <Description2><![CDATA[]]></Description2>
    </Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/system_power.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>SystemPower</Name>
		<Description1><![CDATA[]]></Description1>
		<ObjectID>31415</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31415:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Single</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>Mode</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/obstacle_avoidance.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>ObstacleAvoidance</Name>
		<Description1><![CDATA[]]></Description1>
		<ObjectID>31424</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31424:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Single</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>Available</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="2">
				<Name>Enabled</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="3">
				<Name>UseAtBoundary</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/system-0_3.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
        <Name>System</Name>
        <Description1><![CDATA[system settings of the mower]]></Description1>
        <ObjectID>31403</ObjectID>
        <ObjectURN>urn:oma:lwm2m:x:31403:0.3</ObjectURN>
        <LWM2MVersion>1.1</LWM2MVersion>
        <ObjectVersion>0.3</ObjectVersion>
        <MultipleInstances>Single</MultipleInstances>
        <Mandatory>Optional</Mandatory>
        <Resources>
            <Item ID="1">
                <Name>StartupSequenceRequired</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="2">
                <Name>LocalHmiAvailable</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="3">
                <Name>Model__deviceType</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="4">
                <Name>Model__deviceVariant</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="5">
                <Name>SerialNumber</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="6">
                <Name>ConfigVersionString</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>String</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="7">
                <Name>SwUpdateRequired</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="8">
                <Name>ForcedSwUpdateRequired</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="9">
                <Name>SwPackageVersionString</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>String</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="10">
                <Name>DeviceGroup</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="11">
                <Name>ClearStartupSequenceRequired</Name>
                <Operations>E</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type></Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="12">
                <Name>ResetToUserDefault</Name>
                <Operations>E</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type></Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="13">
                <Name>ApplyConfigDone__Event</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Optional</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Representation of apply config done event (no event data)]]></Description>
            </Item>
            <Item ID="14">
                <Name>ApplyConfigError__Event</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Optional</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Representation of apply config error event (no event data)]]></Description>
            </Item>
        </Resources>
        <Description2><![CDATA[]]></Description2>
    </Object>
</LWM2M>
