=== husqvarnagroup/smart-garden-ipso-registry/3rd-party/LWM2M-v1_1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

LWM2M XML Schema - LWM2M Editor Schema
   version - 1.1
   date    - 2018-07-10

FILE INFORMATION

  Public Reachable Information
    Path: http://www.openmobilealliance.org/tech/profiles
    Name: LWM2M-v1_1.xsd

NORMATIVE INFORMATION

  Information about this file can be found in the LWM2M online editor

  This is available at http://www.openmobilealliance.org/

  Send comments to https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues

CHANGE HISTORY

21112013 First version
06082015 Bug Fix to correct mismatch
18022016 Legal Disclaimer updated from template OMA-TEMPLATE-SUP_XSD_example-20160218-I
24032016 Changed "xs:unsignedshort" to "xs:unsignedShort"
25052016 Incorporated OMA-DM-LightweightM2M-2016-0066R01-INP_CR_Update_LWM2M_xsd
14012017 Introduction of two new elements: LWM2MObject and ObjectVersion
09022018 Introduction of two new types: "CoreLnk" and "Unsigned Integer"
12062018 Prepare for publication
10072018 Prepare for Final Approval

LEGAL DISCLAIMER

  Copyright 2018 Open Mobile Alliance Ltd.  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
  3. Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived
  from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.

  The above license is used as a license under copyright only.  Please
  reference the OMA IPR Policy for patent licensing terms:
  http://www.openmobilealliance.org/ipr.html

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LWM2M">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="Object">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Description1" type="xs:string" />
              <xs:element name="ObjectID" type="xs:unsignedShort" />
              <xs:element name="ObjectURN" type="xs:string" />
              <xs:element name="LWM2MVersion" type="xs:string" minOccurs="0"/>
              <xs:element name="ObjectVersion" type="xs:string" minOccurs="0"/>			  
              <xs:element name="MultipleInstances" >
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Multiple"/>
                    <xs:enumeration value="Single"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Mandatory" >
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Mandatory"/>
                    <xs:enumeration value="Optional"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Resources">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Item">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="xs:string" />
                          <xs:element name="Operations" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="R"/>
                                <xs:enumeration value="W"/>
                                <xs:enumeration value="RW"/>
                                <xs:enumeration value="E"/>
                                <xs:enumeration value=""/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="MultipleInstances" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Multiple"/>
                                <xs:enumeration value="Single"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Mandatory" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Mandatory"/>
                                <xs:enumeration value="Optional"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Type" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="String"/>
                                <xs:enumeration value="Integer"/>
                                <xs:enumeration value="Float"/>
                                <xs:enumeration value="Boolean"/>
                                <xs:enumeration value="Opaque"/>
                                <xs:enumeration value="Time"/>
                                <xs:enumeration value="Objlnk"/>
                                <xs:enumeration value="Unsigned Integer"/>
                                <xs:enumeration value="Corelnk"/>
                                <xs:enumeration value=""/>
                             </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="RangeEnumeration" type="xs:string" />
                          <xs:element name="Units" type="xs:string" />
                          <xs:element name="Description" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="ID" type="xs:unsignedShort" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Description2" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="ObjectType" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/smart_system_mower_api__starting_points.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>SmartSystemMowerApi__StartingPoints</Name>
		<Description1><![CDATA[]]></Description1>
		<ObjectID>31507</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31507:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Multiple</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>enabled</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="2">
				<Name>proportion</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>%</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="3">
				<Name>wire</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="4">
				<Name>distance</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>m</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="5">
				<Name>passageCuttingEnabled</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/gps_navigation-1_0.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
        <Name>GpsNavigation</Name>
        <Description1><![CDATA[]]></Description1>
        <ObjectID>31426</ObjectID>
        <ObjectURN>urn:oma:lwm2m:x:31426:1.0</ObjectURN>
        <LWM2MVersion>1.1</LWM2MVersion>
        <ObjectVersion>1.0</ObjectVersion>
        <MultipleInstances>Single</MultipleInstances>
        <Mandatory>Optional</Mandatory>
        <Resources>
            <Item ID="1">
                <Name>Available</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="2">
                <Name>Enabled</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="3">
                <Name>Status</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="4">
                <Name>Reset</Name>
                <Operations>E</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type></Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
        </Resources>
        <Description2><![CDATA[]]></Description2>
    </Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/position.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>Position</Name>
		<Description1><![CDATA[]]></Description1>
		<ObjectID>31406</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31406:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Single</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>Position__longitude</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>0.1 micro degree</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="2">
				<Name>Position__latitude</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>0.1 micro degree</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="3">
				<Name>Available</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/battery.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>Battery</Name>
		<Description1><![CDATA[]]></Description1>
		<ObjectID>31418</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31418:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Single</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>ChargeLevel</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>%</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="2">
				<Name>Voltage</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>mV</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="3">
				<Name>IsCharging</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="4">
				<Name>RemainingChargingTime</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>s</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="5">
				<Name>Current</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>mA</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="6">
				<Name>Temperature</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>°C</Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/mowerinsights-0_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
        <Name>MowerInsights</Name>
        <Description1><![CDATA[]]></Description1>
        <ObjectID>31428</ObjectID>
        <ObjectURN>urn:oma:lwm2m:x:31428:0.1</ObjectURN>
        <LWM2MVersion>1.1</LWM2MVersion>
        <ObjectVersion>0.1</ObjectVersion>
        <MultipleInstances>Single</MultipleInstances>
        <Mandatory>Optional</Mandatory>
        <Resources>
            <Item ID="1">
                <Name>BatteryCapacity</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>mAh</Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="2">
                <Name>BatteryCurrent</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>mA</Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="3">
                <Name>BatteryNrOfChargingCycles</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="4">
                <Name>BatteryTemperature</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>°C</Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="5">
                <Name>BatteryVoltage</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>mV</Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="6">
                <Name>OrientationPitch</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>0.1°</Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="7">
                <Name>OrientationRoll</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>0.1°</Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="8">
                <Name>StartUpdateTimer</Name>
                <Operations>E</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type></Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
        </Resources>
        <Description2><![CDATA[]]></Description2>
    </Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/mower_app.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>MowerApp</Name>
		<Description1><![CDATA[high level interface of the mower application]]></Description1>
		<ObjectID>31400</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31400:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Single</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>Mode</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="2">
				<Name>State</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="3">
				<Name>Activity</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="4">
				<Name>Error</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="5">
				<Name>IsErrorConfirmable</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="6">
				<Name>Mission</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="7">
				<Name>StartTrigger</Name>
				<Operations>E</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type></Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="8">
				<Name>Pause</Name>
				<Operations>E</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type></Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="9">
				<Name>ConfirmError</Name>
				<Operations>E</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type></Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/system_restart.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
        <Name>SystemRestart</Name>
        <Description1><![CDATA[]]></Description1>
        <ObjectID>31427</ObjectID>
        <ObjectURN>urn:oma:lwm2m:x:31427:0.1</ObjectURN>
        <LWM2MVersion>1.1</LWM2MVersion>
        <ObjectVersion>0.1</ObjectVersion>
        <MultipleInstances>Single</MultipleInstances>
        <Mandatory>Optional</Mandatory>
        <Resources>
            <Item ID="1">
                <Name>RestartReason</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
            <Item ID="2">
                <Name>NormalRestart</Name>
                <Operations>E</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type></Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
        </Resources>
        <Description2><![CDATA[]]></Description2>
    </Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/calendar.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>Calendar</Name>
		<Description1><![CDATA[handler of mowing tasks]]></Description1>
		<ObjectID>31402</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31402:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Single</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>MaxNumberOfTasks</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Max number of tasks]]></Description>
			</Item>
			<Item ID="2">
				<Name>MaxNumberOfTasksPerDay</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Unsigned Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Max number of tasks per day]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[The Calendar handles mowing tasks. Use this module to control at what times and what week days the mower shall be active.

## Task handling
Tasks can be added, modified and deleted. They are accessed using task indexes, which will always be in and uninterrupted range from 0 to number of tasks.

Note! An index of a task is not constant, if a task is deleted the other tasks may have updated indexes. I.e., there is no point in remembering an index of a task for later usage, since it may have been updated.

## Task transaction
If several modifications to the Calendar shall be done at one instance, a transaction shall be used. After a call to StartTransactions, all modifications are done in a sand box until CommitTransaction is performed. If a transaction is not used for 2s, it is discarded.
]]></Description2>
	</Object>
</LWM2M>
