=== husqvarnagroup/smart-garden-ipso-registry/3rd-party/LWM2M-v1_1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

LWM2M XML Schema - LWM2M Editor Schema
   version - 1.1
   date    - 2018-07-10

FILE INFORMATION

  Public Reachable Information
    Path: http://www.openmobilealliance.org/tech/profiles
    Name: LWM2M-v1_1.xsd

NORMATIVE INFORMATION

  Information about this file can be found in the LWM2M online editor

  This is available at http://www.openmobilealliance.org/

  Send comments to https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues

CHANGE HISTORY

21112013 First version
06082015 Bug Fix to correct mismatch
18022016 Legal Disclaimer updated from template OMA-TEMPLATE-SUP_XSD_example-20160218-I
24032016 Changed "xs:unsignedshort" to "xs:unsignedShort"
25052016 Incorporated OMA-DM-LightweightM2M-2016-0066R01-INP_CR_Update_LWM2M_xsd
14012017 Introduction of two new elements: LWM2MObject and ObjectVersion
09022018 Introduction of two new types: "CoreLnk" and "Unsigned Integer"
12062018 Prepare for publication
10072018 Prepare for Final Approval

LEGAL DISCLAIMER

  Copyright 2018 Open Mobile Alliance Ltd.  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
  3. Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived
  from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.

  The above license is used as a license under copyright only.  Please
  reference the OMA IPR Policy for patent licensing terms:
  http://www.openmobilealliance.org/ipr.html

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LWM2M">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="Object">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Description1" type="xs:string" />
              <xs:element name="ObjectID" type="xs:unsignedShort" />
              <xs:element name="ObjectURN" type="xs:string" />
              <xs:element name="LWM2MVersion" type="xs:string" minOccurs="0"/>
              <xs:element name="ObjectVersion" type="xs:string" minOccurs="0"/>			  
              <xs:element name="MultipleInstances" >
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Multiple"/>
                    <xs:enumeration value="Single"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Mandatory" >
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Mandatory"/>
                    <xs:enumeration value="Optional"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Resources">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Item">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="xs:string" />
                          <xs:element name="Operations" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="R"/>
                                <xs:enumeration value="W"/>
                                <xs:enumeration value="RW"/>
                                <xs:enumeration value="E"/>
                                <xs:enumeration value=""/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="MultipleInstances" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Multiple"/>
                                <xs:enumeration value="Single"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Mandatory" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Mandatory"/>
                                <xs:enumeration value="Optional"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Type" >
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="String"/>
                                <xs:enumeration value="Integer"/>
                                <xs:enumeration value="Float"/>
                                <xs:enumeration value="Boolean"/>
                                <xs:enumeration value="Opaque"/>
                                <xs:enumeration value="Time"/>
                                <xs:enumeration value="Objlnk"/>
                                <xs:enumeration value="Unsigned Integer"/>
                                <xs:enumeration value="Corelnk"/>
                                <xs:enumeration value=""/>
                             </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="RangeEnumeration" type="xs:string" />
                          <xs:element name="Units" type="xs:string" />
                          <xs:element name="Description" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="ID" type="xs:unsignedShort" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Description2" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="ObjectType" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== husqvarnagroup/smart-garden-ipso-registry/actuator.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>Actuator</Name>
		<Description1><![CDATA[Generic actuator control for valves, power switch, mower, etc.]]></Description1>
		<ObjectID>28180</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:28180:0.3</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.3</ObjectVersion>
		<MultipleInstances>Multiple</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>default_duration_seconds</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>s</Units>
				<Description><![CDATA[Duration of action started with a physical button. Setting to 0 disables the start on button press.]]></Description>
			</Item>
			<Item ID="2">
				<Name>available</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Boolean</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Indicate whether this actuator is available (e.g. valve connected)]]></Description>
			</Item>
			<Item ID="3">
				<Name>error</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Device and/or actuator specific error]]></Description>
			</Item>
			<Item ID="4">
				<Name>paused_until</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Time</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>s</Units>
				<Description><![CDATA[Scheduled actions paused until seconds from unix epoch]]></Description>
			</Item>
			<Item ID="5">
				<Name>name</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>String</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Name to be used for homekit?]]></Description>
			</Item>
			<Item ID="6">
				<Name>master</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Optional</Mandatory>
				<Type>Objlnk</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Link to master valve object, or (65535,65535) if directly controlled.]]></Description>
			</Item>
			<Item ID="7">
				<Name>current</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Optional</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>mA</Units>
				<Description><![CDATA[Current in mA (optional)]]></Description>
			</Item>
			<Item ID="32">
				<Name>start</Name>
				<Operations>E</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type></Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Start with source (backend, app, homekit, ...) and seconds param. See Timeslot/start_source for more info about sources.
]]></Description>
			</Item>
			<Item ID="33">
				<Name>stop</Name>
				<Operations>E</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type></Type>
				<RangeEnumeration></RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Stop with source (backend or app)]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/position__recent_positions.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
		<Name>Position__RecentPositions</Name>
		<Description1><![CDATA[]]></Description1>
		<ObjectID>31505</ObjectID>
		<ObjectURN>urn:oma:lwm2m:x:31505:0.1</ObjectURN>
		<LWM2MVersion>1.1</LWM2MVersion>
		<ObjectVersion>0.1</ObjectVersion>
		<MultipleInstances>Multiple</MultipleInstances>
		<Mandatory>Optional</Mandatory>
		<Resources>
			<Item ID="1">
				<Name>longitude</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>0.1 micro degree</Units>
				<Description><![CDATA[]]></Description>
			</Item>
			<Item ID="2">
				<Name>latitude</Name>
				<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration></RangeEnumeration>
				<Units>0.1 micro degree</Units>
				<Description><![CDATA[]]></Description>
			</Item>
		</Resources>
		<Description2><![CDATA[]]></Description2>
	</Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/systematicmissions__tasks-0_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: LicenseRef-GARDENA
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
        <Name>SystematicMissions__Tasks</Name>
        <Description1><![CDATA[handler of systematic missions settings per areaId]]></Description1>
        <ObjectID>31510</ObjectID>
        <ObjectURN>urn:oma:lwm2m:x:31510:0.1</ObjectURN>
        <LWM2MVersion>1.1</LWM2MVersion>
        <ObjectVersion>0.1</ObjectVersion>
        <MultipleInstances>Multiple</MultipleInstances>
        <Mandatory>Optional</Mandatory>
        <Resources>
            <Item ID="1">
                <Name>Orientation</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration>[-1800, 1800]</RangeEnumeration>
                <Units>0.1 deg</Units>
                <Description><![CDATA[Orientation used for generating the systematic line segments. 0° is pointing east.]]></Description>
            </Item>
            <Item ID="2">
                <Name>OrientationShift</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration>[-1800, 1800]</RangeEnumeration>
                <Units>0.1 deg</Units>
                <Description><![CDATA[Orientation shift that will be added to the orientation each time the mission is loaded. 
Can be used for creating certain patterns (e.g. checkerboard or diamonds).
]]></Description>
            </Item>
            <Item ID="3">
                <Name>CurrentOrientation</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Integer</Type>
                <RangeEnumeration>[-1800, 1800]</RangeEnumeration>
                <Units>0.1 deg</Units>
                <Description><![CDATA[Orientation shift that will be added to the orientation each time the mission is loaded. 
Can be used for creating certain patterns (e.g. checkerboard or diamonds).
]]></Description>
            </Item>
            <Item ID="4">
                <Name>Boundary</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Indicates if boundary mowing should be mowed or not and how. 
( 0 ) BOUNDARY_DISABLED  : Boundary mowing is disabled
( 1 ) BOUNDARY_FIXED     : The outermost boundary lap will be mowed always with the same fixed track, yielding a well-defined edge.
( 2 ) BOUNDARY_SHIFTING  : The outermost boundary track will always be shifted a bit to reduce the risk of creating wheel tracks in the grass.
]]></Description>
            </Item>
            <Item ID="5">
                <Name>MowingPriority</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[Decide if Area is being mowed first or the boundary.
( 0 ) AREA_FIRST
( 1 ) BOUNDARY_FIRST
]]></Description>
            </Item>
            <Item ID="6">
                <Name>MowingOverlap</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration>[0, 100]</RangeEnumeration>
                <Units>mm</Units>
                <Description><![CDATA[Define the overlap of the mowed lines.]]></Description>
            </Item>
            <Item ID="8">
                <Name>NavigationType</Name>
                <Operations>RW</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[( 0 ) FREE_NAVIGATION
( 1 ) BOUNDARY_NAVIGATION
]]></Description>
            </Item>
            <Item ID="9">
                <Name>Progress</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration>[0, 100]</RangeEnumeration>
                <Units>%</Units>
                <Description><![CDATA[Progress of mowed area]]></Description>
            </Item>
            <Item ID="10">
                <Name>areaId</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>String</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[]]></Description>
            </Item>
        </Resources>
        <Description2><![CDATA[]]></Description2>
    </Object>
</LWM2M>

=== husqvarnagroup/smart-garden-ipso-registry/definitions/eposservice-1_0.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: Copyright (c) 2022 GARDENA GmbH
SPDX-License-Identifier: GPL-3.0-or-later
-->
<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
    <Object ObjectType="MODefinition">
        <Name>EposService</Name>
        <Description1><![CDATA[]]></Description1>
        <ObjectID>31430</ObjectID>
        <ObjectURN>urn:oma:lwm2m:x:31430:1.0</ObjectURN>
        <LWM2MVersion>1.1</LWM2MVersion>
        <ObjectVersion>1.0</ObjectVersion>
        <MultipleInstances>Single</MultipleInstances>
        <Mandatory>Optional</Mandatory>
        <Resources>
            <Item ID="1">
                <Name>Available</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[If the EposService functionality is available]]></Description>
            </Item>
            <Item ID="2">
                <Name>Enabled</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[If the EposService functionality is enabled]]></Description>
            </Item>
            <Item ID="3">
                <Name>ServiceStatus</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[The status of the external EPOS service provider.]]></Description>
            </Item>
            <Item ID="4">
                <Name>SignalQuality</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units>%</Units>
                <Description><![CDATA[Signal quality of correction data stream]]></Description>
            </Item>
            <Item ID="5">
                <Name>HasOrigin</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[If an Origin exists / has been set before]]></Description>
            </Item>
            <Item ID="6">
                <Name>IsOriginValid</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[If the Origin is valid.]]></Description>
            </Item>
            <Item ID="7">
                <Name>IsOriginSettable</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Boolean</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[If the Origin is settable based on current position.]]></Description>
            </Item>
            <Item ID="8">
                <Name>ConnectionStatus</Name>
                <Operations>R</Operations>
                <MultipleInstances>Single</MultipleInstances>
                <Mandatory>Mandatory</Mandatory>
                <Type>Unsigned Integer</Type>
                <RangeEnumeration></RangeEnumeration>
                <Units></Units>
                <Description><![CDATA[The status of the external EPOS connection with respect to backend.]]></Description>
            </Item>
        </Resources>
        <Description2><![CDATA[The EposService module manages the connection and provides information to the "EPOS via Internet" backend. It communicates if the mower wants correction/assist data and provides a way for the backend to communicate its status to the mower.

##### What does "available" mean on this family?
The available flag indicates if this mower supports Epos as a service, i.e. is capable of receiving correction data from backend service. It does not reflect whether this mower has an active subscription, that is unknown to the mower.

##### What does "enabled" mean?
Enabled means that the user has selected to use Epos as a service. If EposService is both available and enabled, the mower will expect to receive correction data when needed.
]]></Description2>
    </Object>
</LWM2M>
